/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.koalatech.login;

import hsqldb_con.CreateDB;
import java.awt.Color;
import javax.swing.JOptionPane;

//testing added october 27, 2014
//jlkasjdlkfskladfjslakdjf

/**
 *
 * @author koala
 * Change logs:
 * login system with password reset
 * user can reset password
 * user can register a new account
 * Only first name, last name, username, password, sec_ques, and sec_ques_ans can
 *  be stored in the table at the moment
 * 
 * Database is not yet modifiable
 * Table is manually supplied
 * 
 * Personal and account details cannot be updated yet
 * 
 * Feb 21
 *  - added greetings through first name
 * 
 * Feb 22
 *  - added keyPressed event on (username and password textbox)
 *  - added keyPressed event on (login button)
 *  - added loginProcess method to handle keyPressed events. (avoid redundant code)
 *  - changed condition in login process
 *  - changed prompt of invalid login
 *  - disabled buttons focusable
 *  - added account logged in as option to main
 */
public class Loginv2 extends javax.swing.JFrame {

    /**
     * Creates new form Loginv2
     */
    public Loginv2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uname_box = new javax.swing.JTextField();
        pword_box = new javax.swing.JPasswordField();
        login_btn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        forget_lbl = new javax.swing.JLabel();
        reg_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        uname_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uname_boxKeyPressed(evt);
            }
        });

        pword_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pword_boxKeyPressed(evt);
            }
        });

        login_btn.setText("Login");
        login_btn.setFocusable(false);
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        login_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login_btnKeyPressed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        forget_lbl.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        forget_lbl.setForeground(new java.awt.Color(0, 51, 204));
        forget_lbl.setText("Forgot Password?");
        forget_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forget_lblMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                forget_lblMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                forget_lblMouseReleased(evt);
            }
        });

        reg_lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        reg_lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        reg_lbl.setText("Register new account?");
        reg_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reg_lblMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reg_lblMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                reg_lblMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pword_box, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(uname_box)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reg_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forget_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(uname_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(pword_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(login_btn))
                .addGap(18, 18, 18)
                .addComponent(reg_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(forget_lbl)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void loginProcess(){
        CreateDB login = new CreateDB(); //call DBConnect
        
         try{
                String select_query = "select * from accounts where "
                                    + "username = ? and "
                                    + "password = ?";
                        
                  login.pst = login.con.prepareStatement(select_query);

                     String myUsername = uname_box.getText();
                     String myPass = (new String(pword_box.getPassword())); //get password and convert to string, toString() not working
                     login.pst.setString(1, myUsername); //username existing (try if myUsername exists in your database)
                     login.pst.setString(2, myPass); //username existing (try if myPass exists in your database)

                  login.rs = login.pst.executeQuery(); //execute query () no need for select_query when using pst

   
                  
                  String username="";
                  String password="";
                  
                  while(login.rs.next()){

                     username = login.rs.getString("username");
                     password = login.rs.getString("password");
                 
                     //debug
                       //System.out.println("Account: " + username +"\n" + "Password: " + password);

                  }//end of while

               
                  if(myUsername.equals(username) && myPass.equals(password) && myUsername.length() != 0 && myPass.length() != 0){
                     JOptionPane.showMessageDialog(this, "Welcome " + username +"!"); //added to display name
//                     MainWindow showMain = new MainWindow();
//                     showMain.setVisible(true);
//                     showMain.account_status.setText("Logged in as: " + username.toUpperCase());
//                     showMain.account_status.setBackground(Color.green);
                     this.setVisible(false);
                  }
                  else{
                     JOptionPane.showMessageDialog(this, "Invalid username or password");
                  }
                  
                  login.con.close();


        }catch(Exception ex){
            System.out.println(ex);
        }//end of catch
    }
    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        
        loginProcess();
        
    }//GEN-LAST:event_login_btnActionPerformed

    private void reg_lblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_lblMousePressed
        // TODO add your handling code here:
              reg_lbl.setForeground(Color.red);
    }//GEN-LAST:event_reg_lblMousePressed

    private void reg_lblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_lblMouseReleased
        // TODO add your handling code here:
              reg_lbl.setForeground(Color.black);
    }//GEN-LAST:event_reg_lblMouseReleased

    private void forget_lblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forget_lblMousePressed
        // TODO add your handling code here:
          forget_lbl.setForeground(Color.red);
    }//GEN-LAST:event_forget_lblMousePressed

    private void forget_lblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forget_lblMouseReleased
        // TODO add your handling code here:
          forget_lbl.setForeground(Color.blue);
    }//GEN-LAST:event_forget_lblMouseReleased

    private void reg_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_lblMouseClicked
        // TODO add your handling code here:
//        NewAccountRegForm showRegForm = new NewAccountRegForm();
//        this.setVisible(false);
//        showRegForm.setVisible(true);
    }//GEN-LAST:event_reg_lblMouseClicked

    private void forget_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forget_lblMouseClicked
        // TODO add your handling code here:
//        ResetPassForm showResetPassForm = new ResetPassForm();
//        this.setVisible(false);
//        showResetPassForm.setVisible(true);
    }//GEN-LAST:event_forget_lblMouseClicked

    private void login_btnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_btnKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            loginProcess();
                
             }
    }//GEN-LAST:event_login_btnKeyPressed

    private void uname_boxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uname_boxKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == evt.VK_ENTER){
            loginProcess();
                
             }
    }//GEN-LAST:event_uname_boxKeyPressed

    private void pword_boxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pword_boxKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == evt.VK_ENTER){
            loginProcess();
                
             }
    }//GEN-LAST:event_pword_boxKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginv2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel forget_lbl;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton login_btn;
    private javax.swing.JPasswordField pword_box;
    private javax.swing.JLabel reg_lbl;
    private javax.swing.JTextField uname_box;
    // End of variables declaration//GEN-END:variables
}
